/**
 * Curated course catalog (N8, F8). Version-controlled here, seeded into the
 * `courses` table. Never model-generated, never a live LLM lookup.
 *
 * ── On verified_at ──────────────────────────────────────────────────────────
 * Entries here carry NO verifiedAt. `pnpm seed:catalog` requests every URL and
 * inserts only the ones that resolve, stamping verifiedAt with that run's date.
 * A dead link therefore cannot enter the database at all — which is the failure
 * specs §16.4 says destroys the Learning tab's credibility in one click.
 * `pnpm check:links` re-runs the same check quarterly against what's already in.
 *
 * ── Selection rules ─────────────────────────────────────────────────────────
 * Free-first. Official vendor documentation and roadmap.sh tracks preferred,
 * because they outlive individual creators' channels. Paid entries only where
 * no credible free path exists, and always labelled as paid.
 */

export interface CourseDef {
  provider: string;
  title: string;
  url: string;
  priceLabel: string;
  lengthLabel: string;
  lengthMinutes: number;
  level: "beginner" | "intermediate" | "advanced";
  /** Two-letter provider mark shown on the card. */
  mark: string;
  isFree: boolean;
  /** Canonical skill names from lib/catalog/skills.ts. Seeding fails on a typo. */
  skills: string[];
}

const roadmap = (
  slug: string,
  title: string,
  skills: string[],
  level: CourseDef["level"] = "beginner",
): CourseDef => ({
  provider: "roadmap.sh",
  title,
  url: `https://roadmap.sh/${slug}`,
  priceLabel: "Free",
  lengthLabel: "Self-paced",
  lengthMinutes: 600,
  level,
  mark: "RS",
  isFree: true,
  skills,
});

export const COURSES: CourseDef[] = [
  /* ---------------------------------------------------------- roadmap.sh */
  roadmap("frontend", "Frontend Developer Roadmap", ["HTML", "CSS", "JavaScript"]),
  roadmap("backend", "Backend Developer Roadmap", ["REST APIs", "SQL", "System Design"]),
  roadmap("react", "React Roadmap", ["React"], "intermediate"),
  roadmap("angular", "Angular Roadmap", ["Angular"], "intermediate"),
  roadmap("vue", "Vue Roadmap", ["Vue.js"], "intermediate"),
  roadmap("javascript", "JavaScript Roadmap", ["JavaScript"]),
  roadmap("typescript", "TypeScript Roadmap", ["TypeScript"], "intermediate"),
  roadmap("nodejs", "Node.js Roadmap", ["Node.js"], "intermediate"),
  roadmap("python", "Python Roadmap", ["Python"]),
  roadmap("java", "Java Roadmap", ["Java"]),
  roadmap("golang", "Go Roadmap", ["Go"], "intermediate"),
  roadmap("rust", "Rust Roadmap", ["Rust"], "advanced"),
  roadmap("sql", "SQL Roadmap", ["SQL"]),
  roadmap("postgresql-dba", "PostgreSQL Roadmap", ["PostgreSQL", "Data Modeling"], "intermediate"),
  roadmap("mongodb", "MongoDB Roadmap", ["MongoDB"], "intermediate"),
  roadmap("docker", "Docker Roadmap", ["Docker"], "intermediate"),
  roadmap("kubernetes", "Kubernetes Roadmap", ["Kubernetes"], "advanced"),
  roadmap("aws", "AWS Roadmap", ["AWS"], "intermediate"),
  roadmap("devops", "DevOps Roadmap", ["CI/CD", "Linux", "Observability"], "intermediate"),
  roadmap("terraform", "Terraform Roadmap", ["Terraform"], "intermediate"),
  roadmap("linux", "Linux Roadmap", ["Linux"]),
  roadmap("system-design", "System Design Roadmap", ["System Design"], "advanced"),
  roadmap("api-design", "API Design Roadmap", ["REST APIs"], "intermediate"),
  roadmap("graphql", "GraphQL Roadmap", ["GraphQL"], "intermediate"),
  roadmap("spring-boot", "Spring Boot Roadmap", ["Spring Boot", "Java"], "intermediate"),
  roadmap("aspnet-core", "ASP.NET Core Roadmap", ["ASP.NET", "C#"], "intermediate"),
  roadmap("php", "PHP Roadmap", ["PHP"]),
  roadmap("android", "Android Roadmap", ["Android Development", "Kotlin"], "intermediate"),
  roadmap("flutter", "Flutter Roadmap", ["Flutter"], "intermediate"),
  roadmap("react-native", "React Native Roadmap", ["React Native", "React"], "intermediate"),
  roadmap("qa", "QA Engineer Roadmap", ["End-to-End Testing", "Unit Testing"], "intermediate"),
  roadmap("cyber-security", "Cyber Security Roadmap", ["Application Security"], "intermediate"),
  roadmap("ai-engineer", "AI Engineer Roadmap", ["LLM Applications"], "intermediate"),
  roadmap("prompt-engineering", "Prompt Engineering Roadmap", ["LLM Applications"]),
  roadmap("mlops", "MLOps Roadmap", ["Machine Learning", "CI/CD"], "advanced"),
  roadmap("data-analyst", "Data Analyst Roadmap", ["SQL", "Data Visualization"]),
  roadmap("code-review", "Code Review Roadmap", ["Code Review"], "intermediate"),
  roadmap("technical-writer", "Technical Writer Roadmap", ["Technical Writing"]),
  roadmap("design-system", "Design System Roadmap", ["Design Systems"], "intermediate"),
  roadmap("ux-design", "UX Design Roadmap", ["UX Research"]),
  roadmap("git-github", "Git and GitHub Roadmap", ["Git"]),

  /* ------------------------------------------------- official docs + tutorials */
  {
    provider: "React",
    title: "Learn React (official tutorial)",
    url: "https://react.dev/learn",
    priceLabel: "Free",
    lengthLabel: "~10 hrs",
    lengthMinutes: 600,
    level: "beginner",
    mark: "RE",
    isFree: true,
    skills: ["React", "JavaScript"],
  },
  {
    provider: "Next.js",
    title: "Learn Next.js — App Router course",
    url: "https://nextjs.org/learn",
    priceLabel: "Free",
    lengthLabel: "~8 hrs",
    lengthMinutes: 480,
    level: "intermediate",
    mark: "NX",
    isFree: true,
    skills: ["Next.js", "React"],
  },
  {
    provider: "Angular",
    title: "Learn Angular — official tutorials",
    url: "https://angular.dev/tutorials/learn-angular",
    priceLabel: "Free",
    lengthLabel: "~4 hrs",
    lengthMinutes: 240,
    level: "beginner",
    mark: "AN",
    isFree: true,
    skills: ["Angular", "TypeScript"],
  },
  {
    provider: "Vue.js",
    title: "Vue Interactive Tutorial",
    url: "https://vuejs.org/tutorial/",
    priceLabel: "Free",
    lengthLabel: "~3 hrs",
    lengthMinutes: 180,
    level: "beginner",
    mark: "VU",
    isFree: true,
    skills: ["Vue.js"],
  },
  {
    provider: "Svelte",
    title: "Svelte Interactive Tutorial",
    url: "https://svelte.dev/tutorial",
    priceLabel: "Free",
    lengthLabel: "~4 hrs",
    lengthMinutes: 240,
    level: "beginner",
    mark: "SV",
    isFree: true,
    skills: ["Svelte"],
  },
  {
    provider: "MDN",
    title: "Learn Web Development",
    url: "https://developer.mozilla.org/en-US/docs/Learn_web_development",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 1200,
    level: "beginner",
    mark: "MD",
    isFree: true,
    skills: ["HTML", "CSS", "JavaScript"],
  },
  {
    provider: "web.dev",
    title: "Learn CSS",
    url: "https://web.dev/learn/css",
    priceLabel: "Free",
    lengthLabel: "~6 hrs",
    lengthMinutes: 360,
    level: "beginner",
    mark: "WD",
    isFree: true,
    skills: ["CSS"],
  },
  {
    provider: "web.dev",
    title: "Learn Accessibility",
    url: "https://web.dev/learn/accessibility",
    priceLabel: "Free",
    lengthLabel: "~5 hrs",
    lengthMinutes: 300,
    level: "beginner",
    mark: "WD",
    isFree: true,
    skills: ["Web Accessibility"],
  },
  {
    provider: "web.dev",
    title: "Learn Performance",
    url: "https://web.dev/learn/performance",
    priceLabel: "Free",
    lengthLabel: "~4 hrs",
    lengthMinutes: 240,
    level: "intermediate",
    mark: "WD",
    isFree: true,
    skills: ["Web Performance"],
  },
  {
    provider: "W3C WAI",
    title: "Web Accessibility Tutorials",
    url: "https://www.w3.org/WAI/tutorials/",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 300,
    level: "intermediate",
    mark: "W3",
    isFree: true,
    skills: ["Web Accessibility"],
  },
  {
    provider: "TypeScript",
    title: "The TypeScript Handbook",
    url: "https://www.typescriptlang.org/docs/handbook/intro.html",
    priceLabel: "Free",
    lengthLabel: "~6 hrs",
    lengthMinutes: 360,
    level: "intermediate",
    mark: "TS",
    isFree: true,
    skills: ["TypeScript"],
  },
  {
    provider: "Tailwind CSS",
    title: "Tailwind CSS Documentation",
    url: "https://tailwindcss.com/docs",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 240,
    level: "beginner",
    mark: "TW",
    isFree: true,
    skills: ["Tailwind CSS", "CSS"],
  },
  {
    provider: "Redux",
    title: "Redux Essentials Tutorial",
    url: "https://redux.js.org/tutorials/essentials/part-1-overview-concepts",
    priceLabel: "Free",
    lengthLabel: "~5 hrs",
    lengthMinutes: 300,
    level: "intermediate",
    mark: "RX",
    isFree: true,
    skills: ["Redux", "React"],
  },
  {
    provider: "Python",
    title: "The Python Tutorial",
    url: "https://docs.python.org/3/tutorial/",
    priceLabel: "Free",
    lengthLabel: "~8 hrs",
    lengthMinutes: 480,
    level: "beginner",
    mark: "PY",
    isFree: true,
    skills: ["Python"],
  },
  {
    provider: "Go",
    title: "A Tour of Go",
    url: "https://go.dev/tour/",
    priceLabel: "Free",
    lengthLabel: "~4 hrs",
    lengthMinutes: 240,
    level: "beginner",
    mark: "GO",
    isFree: true,
    skills: ["Go"],
  },
  {
    provider: "Rust",
    title: "The Rust Programming Language",
    url: "https://doc.rust-lang.org/book/",
    priceLabel: "Free",
    lengthLabel: "~20 hrs",
    lengthMinutes: 1200,
    level: "intermediate",
    mark: "RU",
    isFree: true,
    skills: ["Rust"],
  },
  {
    provider: "Kotlin",
    title: "Kotlin Docs — Getting Started",
    url: "https://kotlinlang.org/docs/getting-started.html",
    priceLabel: "Free",
    lengthLabel: "~4 hrs",
    lengthMinutes: 240,
    level: "beginner",
    mark: "KT",
    isFree: true,
    skills: ["Kotlin"],
  },
  {
    provider: "Node.js",
    title: "Introduction to Node.js",
    url: "https://nodejs.org/en/learn/getting-started/introduction-to-nodejs",
    priceLabel: "Free",
    lengthLabel: "~3 hrs",
    lengthMinutes: 180,
    level: "beginner",
    mark: "ND",
    isFree: true,
    skills: ["Node.js", "JavaScript"],
  },
  {
    provider: "NestJS",
    title: "NestJS — First Steps",
    url: "https://docs.nestjs.com/first-steps",
    priceLabel: "Free",
    lengthLabel: "~4 hrs",
    lengthMinutes: 240,
    level: "intermediate",
    mark: "NS",
    isFree: true,
    skills: ["NestJS", "Node.js", "TypeScript"],
  },
  {
    provider: "Django",
    title: "Writing your first Django app",
    url: "https://docs.djangoproject.com/en/stable/intro/tutorial01/",
    priceLabel: "Free",
    lengthLabel: "~6 hrs",
    lengthMinutes: 360,
    level: "beginner",
    mark: "DJ",
    isFree: true,
    skills: ["Django", "Python"],
  },
  {
    provider: "FastAPI",
    title: "FastAPI Tutorial — User Guide",
    url: "https://fastapi.tiangolo.com/tutorial/",
    priceLabel: "Free",
    lengthLabel: "~5 hrs",
    lengthMinutes: 300,
    level: "intermediate",
    mark: "FA",
    isFree: true,
    skills: ["FastAPI", "Python", "REST APIs"],
  },
  {
    provider: "Flask",
    title: "Flask Tutorial",
    url: "https://flask.palletsprojects.com/en/stable/tutorial/",
    priceLabel: "Free",
    lengthLabel: "~4 hrs",
    lengthMinutes: 240,
    level: "beginner",
    mark: "FL",
    isFree: true,
    skills: ["Flask", "Python"],
  },
  {
    provider: "Spring",
    title: "Building an Application with Spring Boot",
    url: "https://spring.io/guides/gs/spring-boot",
    priceLabel: "Free",
    lengthLabel: "~2 hrs",
    lengthMinutes: 120,
    level: "intermediate",
    mark: "SP",
    isFree: true,
    skills: ["Spring Boot", "Java"],
  },
  {
    provider: "Rails",
    title: "Getting Started with Rails",
    url: "https://guides.rubyonrails.org/getting_started.html",
    priceLabel: "Free",
    lengthLabel: "~6 hrs",
    lengthMinutes: 360,
    level: "beginner",
    mark: "RR",
    isFree: true,
    skills: ["Ruby on Rails", "Ruby"],
  },
  {
    provider: "Microsoft Learn",
    title: "ASP.NET Core Tutorials",
    url: "https://learn.microsoft.com/en-us/aspnet/core/tutorials/",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 480,
    level: "intermediate",
    mark: "MS",
    isFree: true,
    skills: ["ASP.NET", "C#"],
  },
  {
    provider: "GraphQL",
    title: "Introduction to GraphQL",
    url: "https://graphql.org/learn/",
    priceLabel: "Free",
    lengthLabel: "~3 hrs",
    lengthMinutes: 180,
    level: "intermediate",
    mark: "GQ",
    isFree: true,
    skills: ["GraphQL", "REST APIs"],
  },
  {
    provider: "gRPC",
    title: "gRPC Quick Start and Guides",
    url: "https://grpc.io/docs/languages/",
    priceLabel: "Free",
    lengthLabel: "~3 hrs",
    lengthMinutes: 180,
    level: "advanced",
    mark: "GR",
    isFree: true,
    skills: ["gRPC"],
  },
  {
    provider: "MDN",
    title: "WebSockets API Guide",
    url: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API",
    priceLabel: "Free",
    lengthLabel: "~2 hrs",
    lengthMinutes: 120,
    level: "intermediate",
    mark: "MD",
    isFree: true,
    skills: ["WebSockets"],
  },

  /* --------------------------------------------------------------- data */
  {
    provider: "SQLBolt",
    title: "SQLBolt — Interactive SQL Lessons",
    url: "https://sqlbolt.com/",
    priceLabel: "Free",
    lengthLabel: "~3 hrs",
    lengthMinutes: 180,
    level: "beginner",
    mark: "SB",
    isFree: true,
    skills: ["SQL"],
  },
  {
    provider: "PG Exercises",
    title: "PostgreSQL Exercises",
    url: "https://pgexercises.com/",
    priceLabel: "Free",
    lengthLabel: "~5 hrs",
    lengthMinutes: 300,
    level: "intermediate",
    mark: "PE",
    isFree: true,
    skills: ["PostgreSQL", "SQL"],
  },
  {
    provider: "PostgreSQL",
    title: "PostgreSQL Official Tutorial",
    url: "https://www.postgresql.org/docs/current/tutorial.html",
    priceLabel: "Free",
    lengthLabel: "~4 hrs",
    lengthMinutes: 240,
    level: "beginner",
    mark: "PG",
    isFree: true,
    skills: ["PostgreSQL", "SQL", "Data Modeling"],
  },
  {
    provider: "MongoDB",
    title: "MongoDB Learn",
    url: "https://learn.mongodb.com/",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 480,
    level: "beginner",
    mark: "MG",
    isFree: true,
    skills: ["MongoDB"],
  },
  {
    provider: "Redis",
    title: "Redis Developer Docs",
    url: "https://redis.io/docs/latest/develop/",
    priceLabel: "Free",
    lengthLabel: "~3 hrs",
    lengthMinutes: 180,
    level: "intermediate",
    mark: "RD",
    isFree: true,
    skills: ["Redis"],
  },
  {
    provider: "Confluent",
    title: "Apache Kafka Courses",
    url: "https://developer.confluent.io/courses/",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 600,
    level: "intermediate",
    mark: "CF",
    isFree: true,
    skills: ["Apache Kafka", "Message Queues"],
  },
  {
    provider: "Apache Airflow",
    title: "Airflow Tutorials",
    url: "https://airflow.apache.org/docs/apache-airflow/stable/tutorial/",
    priceLabel: "Free",
    lengthLabel: "~4 hrs",
    lengthMinutes: 240,
    level: "intermediate",
    mark: "AF",
    isFree: true,
    skills: ["Airflow", "ETL"],
  },
  {
    provider: "dbt Labs",
    title: "dbt Courses",
    url: "https://learn.getdbt.com/",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 480,
    level: "intermediate",
    mark: "DB",
    isFree: true,
    skills: ["dbt", "ETL", "SQL"],
  },
  {
    provider: "Apache Spark",
    title: "Spark Quick Start",
    url: "https://spark.apache.org/docs/latest/quick-start.html",
    priceLabel: "Free",
    lengthLabel: "~2 hrs",
    lengthMinutes: 120,
    level: "advanced",
    mark: "SK",
    isFree: true,
    skills: ["Apache Spark", "ETL"],
  },
  {
    provider: "pandas",
    title: "Getting Started Tutorials",
    url: "https://pandas.pydata.org/docs/getting_started/intro_tutorials/",
    priceLabel: "Free",
    lengthLabel: "~4 hrs",
    lengthMinutes: 240,
    level: "beginner",
    mark: "PD",
    isFree: true,
    skills: ["Pandas", "Python"],
  },
  {
    provider: "Kaggle",
    title: "Kaggle Learn — Data and ML micro-courses",
    url: "https://www.kaggle.com/learn",
    priceLabel: "Free",
    lengthLabel: "~3 hrs each",
    lengthMinutes: 180,
    level: "beginner",
    mark: "KG",
    isFree: true,
    skills: ["Machine Learning", "Pandas", "Data Visualization"],
  },
  {
    provider: "Snowflake",
    title: "Snowflake Quickstarts",
    url: "https://quickstarts.snowflake.com/",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 300,
    level: "intermediate",
    mark: "SF",
    isFree: true,
    skills: ["Snowflake", "SQL"],
  },

  /* ------------------------------------------------------ cloud + devops */
  {
    provider: "Docker",
    title: "Docker — Get Started Guide",
    url: "https://docs.docker.com/get-started/",
    priceLabel: "Free",
    lengthLabel: "~3 hrs",
    lengthMinutes: 180,
    level: "beginner",
    mark: "DK",
    isFree: true,
    skills: ["Docker"],
  },
  {
    provider: "Kubernetes",
    title: "Kubernetes Basics Tutorial",
    url: "https://kubernetes.io/docs/tutorials/kubernetes-basics/",
    priceLabel: "Free",
    lengthLabel: "~4 hrs",
    lengthMinutes: 240,
    level: "intermediate",
    mark: "K8",
    isFree: true,
    skills: ["Kubernetes", "Docker"],
  },
  {
    provider: "HashiCorp",
    title: "Terraform Tutorials",
    url: "https://developer.hashicorp.com/terraform/tutorials",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 480,
    level: "intermediate",
    mark: "HC",
    isFree: true,
    skills: ["Terraform"],
  },
  {
    provider: "AWS",
    title: "AWS Skill Builder",
    url: "https://skillbuilder.aws/",
    priceLabel: "Free tier available",
    lengthLabel: "Self-paced",
    lengthMinutes: 600,
    level: "intermediate",
    mark: "AW",
    isFree: true,
    skills: ["AWS", "Serverless"],
  },
  {
    provider: "Microsoft Learn",
    title: "Microsoft Learn Training Catalog",
    url: "https://learn.microsoft.com/en-us/training/",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 600,
    level: "beginner",
    mark: "MS",
    isFree: true,
    skills: ["Azure", "Data Visualization"],
  },
  {
    provider: "Google Cloud",
    title: "Google Cloud Skills Boost",
    url: "https://www.cloudskillsboost.google/",
    priceLabel: "Free tier available",
    lengthLabel: "Self-paced",
    lengthMinutes: 600,
    level: "intermediate",
    mark: "GC",
    isFree: true,
    skills: ["Google Cloud", "BigQuery"],
  },
  {
    provider: "GitHub",
    title: "GitHub Actions Documentation",
    url: "https://docs.github.com/en/actions",
    priceLabel: "Free",
    lengthLabel: "~4 hrs",
    lengthMinutes: 240,
    level: "intermediate",
    mark: "GH",
    isFree: true,
    skills: ["CI/CD", "Git"],
  },
  {
    provider: "Linux Journey",
    title: "Linux Journey",
    url: "https://linuxjourney.com/",
    priceLabel: "Free",
    lengthLabel: "~6 hrs",
    lengthMinutes: 360,
    level: "beginner",
    mark: "LJ",
    isFree: true,
    skills: ["Linux", "Bash"],
  },
  {
    provider: "OpenTelemetry",
    title: "OpenTelemetry Documentation",
    url: "https://opentelemetry.io/docs/",
    priceLabel: "Free",
    lengthLabel: "~4 hrs",
    lengthMinutes: 240,
    level: "advanced",
    mark: "OT",
    isFree: true,
    skills: ["Observability"],
  },
  {
    provider: "Prometheus",
    title: "Prometheus Getting Started",
    url: "https://prometheus.io/docs/tutorials/getting_started/",
    priceLabel: "Free",
    lengthLabel: "~2 hrs",
    lengthMinutes: 120,
    level: "intermediate",
    mark: "PM",
    isFree: true,
    skills: ["Observability"],
  },
  {
    provider: "Grafana",
    title: "Grafana Tutorials",
    url: "https://grafana.com/tutorials/",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 240,
    level: "intermediate",
    mark: "GF",
    isFree: true,
    skills: ["Observability", "Data Visualization"],
  },
  {
    provider: "Google SRE",
    title: "Site Reliability Engineering (free books)",
    url: "https://sre.google/books/",
    priceLabel: "Free",
    lengthLabel: "Book",
    lengthMinutes: 1200,
    level: "advanced",
    mark: "SR",
    isFree: true,
    skills: ["Incident Response", "Observability"],
  },
  {
    provider: "Nginx",
    title: "Nginx Beginner's Guide",
    url: "https://nginx.org/en/docs/beginners_guide.html",
    priceLabel: "Free",
    lengthLabel: "~2 hrs",
    lengthMinutes: 120,
    level: "intermediate",
    mark: "NG",
    isFree: true,
    skills: ["Nginx", "Linux"],
  },

  /* ------------------------------------------------------------- testing */
  {
    provider: "Testing Library",
    title: "React Testing Library — Introduction",
    url: "https://testing-library.com/docs/react-testing-library/intro/",
    priceLabel: "Free",
    lengthLabel: "~2 hrs",
    lengthMinutes: 120,
    level: "intermediate",
    mark: "TL",
    isFree: true,
    skills: ["React Testing Library", "Unit Testing", "React"],
  },
  {
    provider: "Vitest",
    title: "Vitest Guide",
    url: "https://vitest.dev/guide/",
    priceLabel: "Free",
    lengthLabel: "~2 hrs",
    lengthMinutes: 120,
    level: "intermediate",
    mark: "VT",
    isFree: true,
    skills: ["Unit Testing"],
  },
  {
    provider: "Jest",
    title: "Jest — Getting Started",
    url: "https://jestjs.io/docs/getting-started",
    priceLabel: "Free",
    lengthLabel: "~2 hrs",
    lengthMinutes: 120,
    level: "beginner",
    mark: "JE",
    isFree: true,
    skills: ["Unit Testing"],
  },
  {
    provider: "Playwright",
    title: "Playwright — Getting Started",
    url: "https://playwright.dev/docs/intro",
    priceLabel: "Free",
    lengthLabel: "~3 hrs",
    lengthMinutes: 180,
    level: "intermediate",
    mark: "PW",
    isFree: true,
    skills: ["End-to-End Testing"],
  },
  {
    provider: "Cypress",
    title: "Cypress Documentation",
    url: "https://docs.cypress.io/",
    priceLabel: "Free",
    lengthLabel: "~3 hrs",
    lengthMinutes: 180,
    level: "intermediate",
    mark: "CY",
    isFree: true,
    skills: ["End-to-End Testing"],
  },

  /* ------------------------------------------------------------ security */
  {
    provider: "OWASP",
    title: "OWASP Top Ten",
    url: "https://owasp.org/www-project-top-ten/",
    priceLabel: "Free",
    lengthLabel: "~3 hrs",
    lengthMinutes: 180,
    level: "intermediate",
    mark: "OW",
    isFree: true,
    skills: ["Application Security"],
  },
  {
    provider: "PortSwigger",
    title: "Web Security Academy",
    url: "https://portswigger.net/web-security",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 900,
    level: "advanced",
    mark: "PS",
    isFree: true,
    skills: ["Application Security"],
  },
  {
    provider: "OAuth.net",
    title: "OAuth 2.0 — Getting Started",
    url: "https://oauth.net/2/",
    priceLabel: "Free",
    lengthLabel: "~2 hrs",
    lengthMinutes: 120,
    level: "intermediate",
    mark: "OA",
    isFree: true,
    skills: ["Authentication"],
  },
  {
    provider: "Cloudflare",
    title: "Learning Centre — SSL and TLS",
    url: "https://www.cloudflare.com/learning/ssl/what-is-ssl/",
    priceLabel: "Free",
    lengthLabel: "~1 hr",
    lengthMinutes: 60,
    level: "beginner",
    mark: "CL",
    isFree: true,
    skills: ["Encryption"],
  },

  /* ------------------------------------------------------------------ ai */
  {
    provider: "AI SDK",
    title: "AI SDK Documentation",
    url: "https://ai-sdk.dev/docs/introduction",
    priceLabel: "Free",
    lengthLabel: "~4 hrs",
    lengthMinutes: 240,
    level: "intermediate",
    mark: "AI",
    isFree: true,
    skills: ["LLM Applications", "TypeScript"],
  },
  {
    provider: "Anthropic",
    title: "Prompt Engineering Overview",
    url: "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview",
    priceLabel: "Free",
    lengthLabel: "~3 hrs",
    lengthMinutes: 180,
    level: "intermediate",
    mark: "AC",
    isFree: true,
    skills: ["LLM Applications"],
  },
  {
    provider: "Hugging Face",
    title: "NLP Course",
    url: "https://huggingface.co/learn/nlp-course",
    priceLabel: "Free",
    lengthLabel: "~15 hrs",
    lengthMinutes: 900,
    level: "advanced",
    mark: "HF",
    isFree: true,
    skills: ["NLP", "Deep Learning", "Machine Learning"],
  },
  {
    provider: "scikit-learn",
    title: "scikit-learn Tutorials",
    url: "https://scikit-learn.org/stable/tutorial/index.html",
    priceLabel: "Free",
    lengthLabel: "~6 hrs",
    lengthMinutes: 360,
    level: "intermediate",
    mark: "SL",
    isFree: true,
    skills: ["Machine Learning", "Python"],
  },
  {
    provider: "PyTorch",
    title: "PyTorch Tutorials",
    url: "https://pytorch.org/tutorials/",
    priceLabel: "Free",
    lengthLabel: "~10 hrs",
    lengthMinutes: 600,
    level: "advanced",
    mark: "PT",
    isFree: true,
    skills: ["Deep Learning", "Python"],
  },
  {
    provider: "pgvector",
    title: "pgvector — Postgres vector search",
    url: "https://github.com/pgvector/pgvector",
    priceLabel: "Free",
    lengthLabel: "~2 hrs",
    lengthMinutes: 120,
    level: "advanced",
    mark: "PV",
    isFree: true,
    skills: ["Vector Databases", "PostgreSQL"],
  },

  /* ------------------------------------------------------- mobile + design */
  {
    provider: "React Native",
    title: "React Native — Get Started",
    url: "https://reactnative.dev/docs/getting-started",
    priceLabel: "Free",
    lengthLabel: "~4 hrs",
    lengthMinutes: 240,
    level: "intermediate",
    mark: "RN",
    isFree: true,
    skills: ["React Native", "React"],
  },
  {
    provider: "Flutter",
    title: "Write your first Flutter app",
    url: "https://docs.flutter.dev/get-started/codelab",
    priceLabel: "Free",
    lengthLabel: "~2 hrs",
    lengthMinutes: 120,
    level: "beginner",
    mark: "FT",
    isFree: true,
    skills: ["Flutter"],
  },
  {
    provider: "Apple",
    title: "SwiftUI Tutorials",
    url: "https://developer.apple.com/tutorials/swiftui",
    priceLabel: "Free",
    lengthLabel: "~6 hrs",
    lengthMinutes: 360,
    level: "beginner",
    mark: "AP",
    isFree: true,
    skills: ["iOS Development", "Swift"],
  },
  {
    provider: "Android",
    title: "Android Basics with Compose",
    url: "https://developer.android.com/courses/android-basics-compose/course",
    priceLabel: "Free",
    lengthLabel: "~30 hrs",
    lengthMinutes: 1800,
    level: "beginner",
    mark: "AD",
    isFree: true,
    skills: ["Android Development", "Kotlin"],
  },
  {
    provider: "Storybook",
    title: "Storybook Tutorials",
    url: "https://storybook.js.org/tutorials/",
    priceLabel: "Free",
    lengthLabel: "~4 hrs",
    lengthMinutes: 240,
    level: "intermediate",
    mark: "ST",
    isFree: true,
    skills: ["Design Systems", "React"],
  },
  {
    provider: "Nielsen Norman Group",
    title: "User Research Articles and Videos",
    url: "https://www.nngroup.com/topic/user-research/",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 300,
    level: "beginner",
    mark: "NN",
    isFree: true,
    skills: ["UX Research"],
  },

  /* ---------------------------------------------------------- practice */
  {
    provider: "Learn Git Branching",
    title: "Learn Git Branching",
    url: "https://learngitbranching.js.org/",
    priceLabel: "Free",
    lengthLabel: "~3 hrs",
    lengthMinutes: 180,
    level: "beginner",
    mark: "LG",
    isFree: true,
    skills: ["Git"],
  },
  {
    provider: "Git",
    title: "Pro Git (book)",
    url: "https://git-scm.com/book/en/v2",
    priceLabel: "Free",
    lengthLabel: "Book",
    lengthMinutes: 900,
    level: "intermediate",
    mark: "GT",
    isFree: true,
    skills: ["Git"],
  },
  {
    provider: "Google",
    title: "Engineering Practices — Code Review",
    url: "https://google.github.io/eng-practices/review/",
    priceLabel: "Free",
    lengthLabel: "~2 hrs",
    lengthMinutes: 120,
    level: "intermediate",
    mark: "GG",
    isFree: true,
    skills: ["Code Review"],
  },
  {
    provider: "Google",
    title: "Technical Writing Courses",
    url: "https://developers.google.com/tech-writing",
    priceLabel: "Free",
    lengthLabel: "~5 hrs",
    lengthMinutes: 300,
    level: "beginner",
    mark: "GG",
    isFree: true,
    skills: ["Technical Writing"],
  },
  {
    provider: "GitHub",
    title: "The System Design Primer",
    url: "https://github.com/donnemartin/system-design-primer",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 1200,
    level: "advanced",
    mark: "GH",
    isFree: true,
    skills: ["System Design", "Microservices"],
  },
  {
    provider: "Refactoring Guru",
    title: "Design Patterns",
    url: "https://refactoring.guru/design-patterns",
    priceLabel: "Free (paid book optional)",
    lengthLabel: "Self-paced",
    lengthMinutes: 600,
    level: "intermediate",
    mark: "RG",
    isFree: true,
    skills: ["System Design"],
  },
  {
    provider: "12factor.net",
    title: "The Twelve-Factor App",
    url: "https://12factor.net/",
    priceLabel: "Free",
    lengthLabel: "~1 hr",
    lengthMinutes: 60,
    level: "intermediate",
    mark: "TF",
    isFree: true,
    skills: ["System Design", "Microservices"],
  },
  {
    provider: "Microservices.io",
    title: "Microservice Architecture Patterns",
    url: "https://microservices.io/patterns/",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 480,
    level: "advanced",
    mark: "MI",
    isFree: true,
    skills: ["Microservices", "System Design"],
  },
  {
    provider: "Atlassian",
    title: "Agile Coach — Scrum and Kanban",
    url: "https://www.atlassian.com/agile",
    priceLabel: "Free",
    lengthLabel: "~3 hrs",
    lengthMinutes: 180,
    level: "beginner",
    mark: "AT",
    isFree: true,
    skills: ["Agile"],
  },
  {
    provider: "Scrum.org",
    title: "What is Scrum?",
    url: "https://www.scrum.org/resources/what-is-scrum",
    priceLabel: "Free",
    lengthLabel: "~1 hr",
    lengthMinutes: 60,
    level: "beginner",
    mark: "SC",
    isFree: true,
    skills: ["Agile"],
  },
  {
    provider: "exercism",
    title: "Exercism — Practice Tracks",
    url: "https://exercism.org/",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 600,
    level: "beginner",
    mark: "EX",
    isFree: true,
    skills: ["Python", "JavaScript", "Go", "Rust", "Java"],
  },
  {
    provider: "Harvard",
    title: "CS50x — Introduction to Computer Science",
    url: "https://cs50.harvard.edu/x/",
    priceLabel: "Free (paid certificate)",
    lengthLabel: "~100 hrs",
    lengthMinutes: 6000,
    level: "beginner",
    mark: "CS",
    isFree: true,
    skills: ["C++", "Python", "SQL"],
  },
  {
    provider: "freeCodeCamp",
    title: "freeCodeCamp Curriculum",
    url: "https://www.freecodecamp.org/learn",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 3000,
    level: "beginner",
    mark: "FC",
    isFree: true,
    skills: ["JavaScript", "HTML", "CSS", "Python", "React"],
  },
  {
    provider: "Supabase",
    title: "Supabase Documentation",
    url: "https://supabase.com/docs",
    priceLabel: "Free",
    lengthLabel: "Self-paced",
    lengthMinutes: 300,
    level: "intermediate",
    mark: "SU",
    isFree: true,
    skills: ["PostgreSQL", "Authentication"],
  },
];

/** Sanity guard used by the seed script — a typo'd skill name fails loudly. */
export const CATALOG_SKILL_NAMES = [...new Set(COURSES.flatMap((c) => c.skills))];
